name: Test-Build
on:
  push:
    branches:
      - main
      - develop

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "node"  # Use the latest stable version

      # Install Newman and Reporter
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Run Postman Collection and Generate Report
      - name: Run Postman Collection
        run: |
          mkdir -p testResults
          newman run Demo-My.postman_collection.json \
            -r htmlextra \
            --reporter-htmlextra-export testResults/htmlreport.html \
            --reporter-htmlextra-darkTheme

      # Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git fetch origin
          git checkout -B gh-pages
          git rm -rf .  # Clean the branch to avoid leftovers
          mv testResults/htmlreport.html index.html  # Rename report to index.html for easier access
          git add index.html
          git commit -m "Deploy test report"
          git push origin gh-pages --force
