name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Install Node.js version 18 (LTS)
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"  # Use Node.js 18 LTS

      # Update npm and install punycode
      - name: Install and Update Dependencies
        run: |
          npm install -g npm  # Update npm to the latest version
          npm install punycode  # Install punycode module

      # Install Newman and the Newman Reporter
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Create a directory for test results
      - name: Create Directory for Test Results
        run: mkdir -p testResults

      # Run the Postman collection with suppressed deprecation warnings
      - name: Run Postman Collection
        run: |
          node --no-warnings $(which newman) run store2.postman_collection.json \
          -r htmlextra \
          --reporter-htmlextra-export testResults/htmlreport.html \
          --reporter-htmlextra-darkTheme \
          > testResults/runreport1.html || exit 1  # Ensure failure is handled

      # Upload the test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: testResults
