name: Test-Build

on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Install the latest Node.js version
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "node"  # This will use the latest stable Node.js version

      # Update npm packages
      - name: Update npm packages
        run: npm update

      # Install Newman and the Newman Reporter
      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Create a directory for test results
      - name: Create Directory for Test Results
        run: mkdir -p testResults

      # Run the Postman collection
      - name: Run Postman Collection
        run: |
          newman run petstore.collection.json \
          -r htmlextra \
          --reporter-htmlextra-export testResults/htmlreport.html \
          --reporter-htmlextra-darkTheme

      # Upload the test results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: TestResults
          path: testResults
